
package com.ebssystem;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSEstadoCuentaCygnusSoap", targetNamespace = "http://www.ebssystem.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSEstadoCuentaCygnusSoap {


    /**
     * Consulta las cuentas del cliente
     * 
     * @param xcProducto
     * @param xiTipoIden
     * @param xcIdentificacion
     * @return
     *     returns com.ebssystem.ArrayOfDatoDTO
     */
    @WebMethod(operationName = "WS_CONSULTAR_ESTADOCUENTAISERVICE", action = "http://www.ebssystem.com/WS_CONSULTAR_ESTADOCUENTAISERVICE")
    @WebResult(name = "WS_CONSULTAR_ESTADOCUENTAISERVICEResult", targetNamespace = "http://www.ebssystem.com/")
    @RequestWrapper(localName = "WS_CONSULTAR_ESTADOCUENTAISERVICE", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARESTADOCUENTAISERVICE")
    @ResponseWrapper(localName = "WS_CONSULTAR_ESTADOCUENTAISERVICEResponse", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARESTADOCUENTAISERVICEResponse")
    public ArrayOfDatoDTO wsCONSULTARESTADOCUENTAISERVICE(
        @WebParam(name = "xi_tipo_iden", targetNamespace = "http://www.ebssystem.com/")
        String xiTipoIden,
        @WebParam(name = "xc_identificacion", targetNamespace = "http://www.ebssystem.com/")
        String xcIdentificacion,
        @WebParam(name = "xc_producto", targetNamespace = "http://www.ebssystem.com/")
        String xcProducto);

    /**
     * Consulta los movimientos de una cuenta
     * 
     * @param xcProducto
     * @param xnumProducto
     * @return
     *     returns com.ebssystem.Movimiento
     */
    @WebMethod(operationName = "WS_CONSULTAR_ESTADOCUENTAIISERVICE", action = "http://www.ebssystem.com/WS_CONSULTAR_ESTADOCUENTAIISERVICE")
    @WebResult(name = "WS_CONSULTAR_ESTADOCUENTAIISERVICEResult", targetNamespace = "http://www.ebssystem.com/")
    @RequestWrapper(localName = "WS_CONSULTAR_ESTADOCUENTAIISERVICE", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARESTADOCUENTAIISERVICE")
    @ResponseWrapper(localName = "WS_CONSULTAR_ESTADOCUENTAIISERVICEResponse", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARESTADOCUENTAIISERVICEResponse")
    public Movimiento wsCONSULTARESTADOCUENTAIISERVICE(
        @WebParam(name = "xnum_producto", targetNamespace = "http://www.ebssystem.com/")
        String xnumProducto,
        @WebParam(name = "xc_producto", targetNamespace = "http://www.ebssystem.com/")
        String xcProducto);

    /**
     * Consulta los datos basicos de la cuenta
     * 
     * @param xcProducto
     * @param xnumProducto
     * @return
     *     returns com.ebssystem.ArrayOfDato2DTO
     */
    @WebMethod(operationName = "WS_CONSULTAR_ESTADOCUENTAIIISERVICE", action = "http://www.ebssystem.com/WS_CONSULTAR_ESTADOCUENTAIIISERVICE")
    @WebResult(name = "WS_CONSULTAR_ESTADOCUENTAIIISERVICEResult", targetNamespace = "http://www.ebssystem.com/")
    @RequestWrapper(localName = "WS_CONSULTAR_ESTADOCUENTAIIISERVICE", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARESTADOCUENTAIIISERVICE")
    @ResponseWrapper(localName = "WS_CONSULTAR_ESTADOCUENTAIIISERVICEResponse", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARESTADOCUENTAIIISERVICEResponse")
    public ArrayOfDato2DTO wsCONSULTARESTADOCUENTAIIISERVICE(
        @WebParam(name = "xnum_producto", targetNamespace = "http://www.ebssystem.com/")
        String xnumProducto,
        @WebParam(name = "xc_producto", targetNamespace = "http://www.ebssystem.com/")
        String xcProducto);

    /**
     * Consulta las cuentas del cliente para un extracto
     * 
     * @param xcProducto
     * @param xiTipoIden
     * @param xcIdentificacion
     * @return
     *     returns com.ebssystem.ArrayOfDato3DTO
     */
    @WebMethod(operationName = "WS_CONSULTAR_EXTRACTO", action = "http://www.ebssystem.com/WS_CONSULTAR_EXTRACTO")
    @WebResult(name = "WS_CONSULTAR_EXTRACTOResult", targetNamespace = "http://www.ebssystem.com/")
    @RequestWrapper(localName = "WS_CONSULTAR_EXTRACTO", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTAREXTRACTO")
    @ResponseWrapper(localName = "WS_CONSULTAR_EXTRACTOResponse", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTAREXTRACTOResponse")
    public ArrayOfDato3DTO wsCONSULTAREXTRACTO(
        @WebParam(name = "xi_tipo_iden", targetNamespace = "http://www.ebssystem.com/")
        String xiTipoIden,
        @WebParam(name = "xc_identificacion", targetNamespace = "http://www.ebssystem.com/")
        String xcIdentificacion,
        @WebParam(name = "xc_producto", targetNamespace = "http://www.ebssystem.com/")
        String xcProducto);

    /**
     * Consulta los movimientos de una cuenta por fecha
     * 
     * @param xcProducto
     * @param sFechaInicio
     * @param xnumProducto
     * @param sFechaFin
     * @return
     *     returns com.ebssystem.Movimiento
     */
    @WebMethod(operationName = "WS_CONSULTAR_MOVIMIENTOS_FECHA", action = "http://www.ebssystem.com/WS_CONSULTAR_MOVIMIENTOS_FECHA")
    @WebResult(name = "WS_CONSULTAR_MOVIMIENTOS_FECHAResult", targetNamespace = "http://www.ebssystem.com/")
    @RequestWrapper(localName = "WS_CONSULTAR_MOVIMIENTOS_FECHA", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARMOVIMIENTOSFECHA")
    @ResponseWrapper(localName = "WS_CONSULTAR_MOVIMIENTOS_FECHAResponse", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARMOVIMIENTOSFECHAResponse")
    public Movimiento wsCONSULTARMOVIMIENTOSFECHA(
        @WebParam(name = "xnum_producto", targetNamespace = "http://www.ebssystem.com/")
        String xnumProducto,
        @WebParam(name = "xc_producto", targetNamespace = "http://www.ebssystem.com/")
        String xcProducto,
        @WebParam(name = "sFechaInicio", targetNamespace = "http://www.ebssystem.com/")
        String sFechaInicio,
        @WebParam(name = "sFechaFin", targetNamespace = "http://www.ebssystem.com/")
        String sFechaFin);

    /**
     * Consulta el detalle de una cuenta
     * 
     * @param xcProducto
     * @param sNumRadic
     * @return
     *     returns com.ebssystem.DetalleCta
     */
    @WebMethod(operationName = "WS_OBTENER_DETALLE_CUENTA", action = "http://www.ebssystem.com/WS_OBTENER_DETALLE_CUENTA")
    @WebResult(name = "WS_OBTENER_DETALLE_CUENTAResult", targetNamespace = "http://www.ebssystem.com/")
    @RequestWrapper(localName = "WS_OBTENER_DETALLE_CUENTA", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSOBTENERDETALLECUENTA")
    @ResponseWrapper(localName = "WS_OBTENER_DETALLE_CUENTAResponse", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSOBTENERDETALLECUENTAResponse")
    public DetalleCta wsOBTENERDETALLECUENTA(
        @WebParam(name = "sNumRadic", targetNamespace = "http://www.ebssystem.com/")
        String sNumRadic,
        @WebParam(name = "xc_producto", targetNamespace = "http://www.ebssystem.com/")
        String xcProducto);

    /**
     * Consulta el detalle de un  moviiento por una cuenta
     * 
     * @param xcProducto
     * @param codOperation
     * @param xnumProducto
     * @return
     *     returns com.ebssystem.Movimiento
     */
    @WebMethod(operationName = "WS_OBTENER_DETALLE_MOVIMIENTO", action = "http://www.ebssystem.com/WS_OBTENER_DETALLE_MOVIMIENTO")
    @WebResult(name = "WS_OBTENER_DETALLE_MOVIMIENTOResult", targetNamespace = "http://www.ebssystem.com/")
    @RequestWrapper(localName = "WS_OBTENER_DETALLE_MOVIMIENTO", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSOBTENERDETALLEMOVIMIENTO")
    @ResponseWrapper(localName = "WS_OBTENER_DETALLE_MOVIMIENTOResponse", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSOBTENERDETALLEMOVIMIENTOResponse")
    public Movimiento wsOBTENERDETALLEMOVIMIENTO(
        @WebParam(name = "xnum_producto", targetNamespace = "http://www.ebssystem.com/")
        String xnumProducto,
        @WebParam(name = "cod_operation", targetNamespace = "http://www.ebssystem.com/")
        String codOperation,
        @WebParam(name = "xc_producto", targetNamespace = "http://www.ebssystem.com/")
        String xcProducto);

    /**
     * Consulta los creditos del cliente terminados
     * 
     * @param xiCodigo
     * @param xcProducto
     * @return
     *     returns com.ebssystem.ArrayOfDatoDTO
     */
    @WebMethod(operationName = "WS_CONSULTAR_CREDITOS_TERMINADOS", action = "http://www.ebssystem.com/WS_CONSULTAR_CREDITOS_TERMINADOS")
    @WebResult(name = "WS_CONSULTAR_CREDITOS_TERMINADOSResult", targetNamespace = "http://www.ebssystem.com/")
    @RequestWrapper(localName = "WS_CONSULTAR_CREDITOS_TERMINADOS", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARCREDITOSTERMINADOS")
    @ResponseWrapper(localName = "WS_CONSULTAR_CREDITOS_TERMINADOSResponse", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARCREDITOSTERMINADOSResponse")
    public ArrayOfDatoDTO wsCONSULTARCREDITOSTERMINADOS(
        @WebParam(name = "xi_codigo", targetNamespace = "http://www.ebssystem.com/")
        String xiCodigo,
        @WebParam(name = "xc_producto", targetNamespace = "http://www.ebssystem.com/")
        String xcProducto);

    /**
     * Consulta los amparados de un aporte
     * 
     * @param xcProducto
     * @param sNumRadic
     * @return
     *     returns com.ebssystem.ArrayOfDetalleAmparadoBenef
     */
    @WebMethod(operationName = "WS_CONSULTAR_DATOS_AMPARADOS_BENEFICIARIO", action = "http://www.ebssystem.com/WS_CONSULTAR_DATOS_AMPARADOS_BENEFICIARIO")
    @WebResult(name = "WS_CONSULTAR_DATOS_AMPARADOS_BENEFICIARIOResult", targetNamespace = "http://www.ebssystem.com/")
    @RequestWrapper(localName = "WS_CONSULTAR_DATOS_AMPARADOS_BENEFICIARIO", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARDATOSAMPARADOSBENEFICIARIO")
    @ResponseWrapper(localName = "WS_CONSULTAR_DATOS_AMPARADOS_BENEFICIARIOResponse", targetNamespace = "http://www.ebssystem.com/", className = "com.ebssystem.WSCONSULTARDATOSAMPARADOSBENEFICIARIOResponse")
    public ArrayOfDetalleAmparadoBenef wsCONSULTARDATOSAMPARADOSBENEFICIARIO(
        @WebParam(name = "sNumRadic", targetNamespace = "http://www.ebssystem.com/")
        String sNumRadic,
        @WebParam(name = "xc_producto", targetNamespace = "http://www.ebssystem.com/")
        String xcProducto);

}
